10. Сетка на флексах для внутренней страницы
htmlacademy-htmlcss/1408611-technomart-30 pull request #10
Opened 2021-03-13 17:46 UTC by ayqod

2021-03-13 20:55 UTC, Shramkoweb requested changes

2021-03-13 20:55 UTC, Shramkoweb commented on catalog.html
> +              <img src="/img/icons/icon-user.png" alt="">
Добавь role="presentation" и aria-hidden="true"

2021-03-13 20:55 UTC, Shramkoweb commented on catalog.html
> +              <a class="breadcrumb-link breadcrumb-current" href="#">Перфораторы</a>
Тут не должно быть href - это же текущая ссылка

2021-03-13 20:55 UTC, Shramkoweb commented on css/style.css
> +    margin-right: 18px;
Поплыло =)

2021-03-13 21:09 UTC, ayqod commented on catalog.html
> +              <img src="/img/icons/icon-user.png" alt="">
✅

2021-03-13 21:10 UTC, ayqod commented on catalog.html
> +              <a class="breadcrumb-link breadcrumb-current" href="#">Перфораторы</a>
✅

2021-03-14 06:44 UTC, Shramkoweb approved these changes

2021-03-14 06:44 UTC, merged