12. Декоративные элементы на внутренней странице
htmlacademy-htmlcss/1408611-technomart-30 pull request #12
Opened 2021-03-17 14:43 UTC by ayqod

2021-03-17 17:38 UTC, Shramkoweb requested changes

2021-03-17 17:38 UTC, Shramkoweb commented on catalog.html
> +                <span class="filter-divider"> — </span>
:before ?

2021-03-17 17:38 UTC, Shramkoweb commented on catalog.html
> +                </label>
А где текстовое описание для лейбла?

2021-03-17 17:38 UTC, Shramkoweb commented on catalog.html
> +                </label>
Описание текстовое для лейбла?

2021-03-17 17:38 UTC, Shramkoweb commented on catalog.html
> +                  <label class="brand-checkbox" for="filter-BOSCH">Bosch</label>
делай все id и т/д значения атрибутов в `snake-case`

2021-03-17 17:38 UTC, Shramkoweb commented on catalog.html
> +                  <label class="brand-checkbox" for="filter-BOSCH">Bosch</label>
В некоторых случаях могут быть проблемы с разными типами, поэтому лучше придерживаться одного стиля

2021-03-17 17:38 UTC, Shramkoweb commented on css/style.css
> +.brand-name input:checked+label::before {
```suggestion
.brand-name input:checked + label::before {
```

2021-03-17 22:27 UTC, ayqod commented on catalog.html
> +                <span class="filter-divider"> — </span>
✅

2021-03-17 22:56 UTC, ayqod commented on catalog.html
> +                </label>
Могу дать текстовое описание лейблу, но тогда мне его придется скрывать через vidually hidden. Что тоже конечно можно сделать, но тогда каким образом сделать divider через label::before (как ты предложил выше), если мы знаем, что input'у нельзя задать ни :before ни :after?

2021-03-17 23:06 UTC, ayqod commented on catalog.html
> +                </label>
При таком раскладе не знаю как это сделать кроме как добавив туда span между ними, но при этом все через  :before как ты писал.

2021-03-17 23:06 UTC, ayqod commented on catalog.html
> +                </label>
✅

2021-03-17 23:06 UTC, ayqod commented on catalog.html
> +                </label>
> А где текстовое описание для лейбла?

✅

2021-03-17 23:10 UTC, ayqod commented on catalog.html
> +                  <label class="brand-checkbox" for="filter-BOSCH">Bosch</label>
✅

2021-03-17 23:11 UTC, ayqod commented on css/style.css
> +.brand-name input:checked+label::before {
✅

2021-03-18 12:07 UTC, Shramkoweb approved these changes
LGTM

2021-03-18 12:07 UTC, merged