2. Разметка главной страницы
htmlacademy-htmlcss/1408611-technomart-30 pull request #2
Opened 2021-01-24 14:12 UTC by ayqod

2021-01-24 14:19 UTC, ayqod commented on index.html
> +              <p><s>32500 Р.</s></p>
Я так и не понял основной разницы `<del>` от `<s>`, из описания обоих показалось, что семантически второй тег более подходит под эту ситуацию.

2021-01-24 14:19 UTC, ayqod commented on index.html
> +        <span>г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</span>
Намного ниже и позже вспомнил про тег `<address>`.
Здесь тоже на него поменяю.

2021-01-24 14:19 UTC, ayqod commented on index.html
> +      <p>&copy;2010–2019 Компания «Техномарт» Все права защищены</p>
Не знаю насколько правильно знак копирайта указывать таким путем в разметке. Сомневаюсь.

2021-01-24 14:39 UTC, Shramkoweb commented on index.html
> +              <p><s>32500 Р.</s></p>
Да ты прав. `s` - это по сути "устаревший, не релевантный".
`del` - это когда, ты что-то удалил. 

---
`s` нам сейчас более уместно

2021-01-24 14:40 UTC, Shramkoweb commented on index.html
> +      <p>&copy;2010–2019 Компания «Техномарт» Все права защищены</p>
Корректно

2021-01-24 14:50 UTC, Shramkoweb requested changes

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +    <!-- HEADER -->
Тебе помогают эти коменты?

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <a href="./index.html" title="Главная страница Техномарт">
На главно нам не нужны ссылки опять на главную? Зачем?

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <input type="search" name="search" placeholder="Поиск:">
Где лейбл?

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <h1>Интернет-магазин строительных материалов<br> и инструментов для ремонта</h1>
Насколько я помню - у тайтлов не глобальная видимость, и этот `h1` будет относиться только к этому блоку. Это ок для тебя?

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +      <nav>
Можно будет в будущем если время будет, улучшить наши навигации дам им разные смыслы. Так как сейчас у тебя аж 3 навигации, сложно)

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <h2 hidden>Интернет-магазин "Техномарт"</h2>
Это блок материалов, и услуг сайта. А не весь сайт

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        </header>
Ничего себе =)

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +              <a href="#" title="Перфоратор Bosch BFG 9000">Перфоратор Bosch BFG 9000</a>
Вроде делают наоборот, что-то оборачивают в ссылку.

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +              <a href="#" title="Перфоратор Bosch BFG 9000">Перфоратор Bosch BFG 9000</a>
Но это не точно, можешь найти варианты в статьях или в демках где именно так делают?

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +          </p>
```suggestion
          <p>
              Хороший интернет-магазин отличается от плохого не только ценами!
              Мы стараемся изо всех сил, чтобы сделать ваши покупки приятными.
          </p>
```

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <div>
Заголовок есть а section или artilсle нет =)

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <div>
Аналогично выше

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <div>
Аналогично

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <p>Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для
Форматирование

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <p>Мы можем доставить ваш товар в самые отдаленные точки России!
Форматирование:

```
<p>
  Мы можем доставить ваш товар в самые отдаленные точки России!
  Техномарт работает со многими транспортными компаниями:
</p>
```

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <p>Вы можете забрать товар сами,
Форматирование

2021-01-24 14:50 UTC, Shramkoweb commented on index.html
> +        <h2 hidden>Главная страница Техномарт</h2>
Что это ? Зачем?

2021-01-24 15:02 UTC, ayqod commented on index.html
> +    <!-- HEADER -->
Глаз цепляется за них, когда листаю в поисках раздела нужного.
За что ты их не любишь так?)

2021-01-24 15:07 UTC, ayqod commented on index.html
> +        <a href="./index.html" title="Главная страница Техномарт">
Чтобы обновить интернет-страницу ))) 
Блин, ну просто так делают же многие: хтмл академия, почта gmail, главная страница mozilla и прочие.
Типа "как обновить страницу?" -- просто нажми на логотип)) Разве нет?

2021-01-24 15:10 UTC, ayqod commented on index.html
> +    <!-- HEADER -->
✅

2021-01-24 15:11 UTC, Shramkoweb commented on index.html
> +    <!-- HEADER -->
Ну если тебе помогают =)

2021-01-24 15:11 UTC, Shramkoweb commented on index.html
> +        <a href="./index.html" title="Главная страница Техномарт">
Уговорил =)

2021-01-24 15:11 UTC, ayqod commented on index.html
> +    <!-- HEADER -->
Та если честно, то не особо. Больше по привычке делал. Уже удалил.

2021-01-24 16:15 UTC, ayqod commented on index.html
> +      <nav>
Если за тег `nav` говорить, то всего 2 навигации же, не 3. Отдельно читал пару статей + спецификацию на тему того можно ли использовать несколько раз `nav` на странице. Пишут, что можно. Может потом конечно сложности будут вылазить, тогда буду менять. Классы у них у каждого свои будут. Либо я чет не понимаю:)

2021-01-24 16:21 UTC, ayqod commented on index.html
> +        <input type="search" name="search" placeholder="Поиск:">
А если просто уберу тогда `name`, а остальное оставлю таким же -- ошибкой не будет?

2021-01-24 16:32 UTC, ayqod commented on index.html
> +        <h1>Интернет-магазин строительных материалов<br> и инструментов для ремонта</h1>
Пока не знаю, как тут поступить более правильно. 
Есть вариант выше над логотипом написать `<h1>Интернет-магазин Техномарт</h1>` и скрыть его через CSS потом, но в реальной жизни такое ничего не даст (кроме проверки дерева хтмл), а гугл еще заподозрит в клоакинге.

2021-01-24 16:38 UTC, ayqod commented on index.html
> +        <h1>Интернет-магазин строительных материалов<br> и инструментов для ремонта</h1>
Помещать внутрь тега `h1` например `<a>Техномарт</a>` -- тоже вроде не самая лучшая идея. В дизайне по сути как такового заголовка не предусмотрено.

2021-01-24 17:16 UTC, ayqod commented on index.html
> +        <h1>Интернет-магазин строительных материалов<br> и инструментов для ремонта</h1>
✅

2021-01-24 17:24 UTC, Shramkoweb commented on index.html
> +        <input type="search" name="search" placeholder="Поиск:">
Будет, лейб нужен любому инпуту

2021-01-24 17:25 UTC, Shramkoweb commented on index.html
> +      <nav>
Да все ок, ты прав. Я просто помню, что что-то есть из Aria специфики, чтобы разделять по смыслу разные nav
Пока не парься, это я так к слову

2021-01-24 17:37 UTC, ayqod commented on index.html
> +        <input type="search" name="search" placeholder="Поиск:">
Но именно у этого поля нет никакой подписи...Надпись "поиск" это к placeholder относится. Как тогда в таких случаях поступать? Тоже потом скрывать через цсс?

2021-01-24 17:41 UTC, ayqod commented on index.html
> +        <input type="search" name="search" placeholder="Поиск:">
```suggestion
        <form action="https://htmlacademy.ru" method="POST">
        <label for="search"></label>
        <input type="search" name="search" placeholder="Поиск:">
      </form>
```
Просто вот так?

2021-01-24 17:43 UTC, ayqod commented on index.html
> +        <h2 hidden>Интернет-магазин "Техномарт"</h2>
✅

2021-01-24 17:50 UTC, ayqod commented on index.html
> +        </header>
Сам в шоке ✅

2021-01-24 19:35 UTC, ayqod commented on index.html
> +          </p>
✅

2021-01-24 19:36 UTC, ayqod commented on index.html
> +        <p>Настоящий мужской шоппинг начинается здесь! Огромный выбор товаров для
✅

2021-01-24 19:36 UTC, ayqod commented on index.html
> +        <p>Мы можем доставить ваш товар в самые отдаленные точки России!
✅

2021-01-24 19:36 UTC, ayqod commented on index.html
> +        <p>Вы можете забрать товар сами,
✅

2021-01-24 20:46 UTC, ayqod commented on index.html
> +        <div>
Так [вроде есть же](https://github.com/ayqod/1408611-technomart-30/blob/d7c708b2aad85657a375d15c22e2a0456fa9c8eb/index.html#L210)

2021-01-24 20:59 UTC, ayqod commented on index.html
> +        <h2 hidden>Главная страница Техномарт</h2>
✅

2021-01-24 21:12 UTC, ayqod commented on index.html
> +        <div>
Убрал дивы, сделал списком ul > li

2021-01-24 23:03 UTC, ayqod commented on index.html
> +              <a href="#" title="Перфоратор Bosch BFG 9000">Перфоратор Bosch BFG 9000</a>
Они вообще не должны быть ссылками, судя по стайлгайду. 
Так шо я прекращаю это безумие прямо сейчас.

2021-01-24 23:03 UTC, ayqod commented on index.html
> +        <div>
✅

2021-01-24 23:22 UTC, ayqod commented on index.html
> +              <a href="#" title="Перфоратор Bosch BFG 9000">Перфоратор Bosch BFG 9000</a>
✅

2021-01-25 20:06 UTC, Shramkoweb approved these changes
👍

2021-01-25 20:06 UTC, merged