3. Разметка внутренней страницы
htmlacademy-htmlcss/1408611-technomart-30 pull request #3
Opened 2021-01-27 01:40 UTC by ayqod

2021-01-27 01:58 UTC, ayqod commented on catalog.html
> +      <ol>
Использовал тут упорядоченный список, потому что по смыслы тут действительно важно значение поочередности.

2021-01-27 01:58 UTC, ayqod commented on catalog.html
> +                <input type="checkbox" name="brands" value="Bosch" id="filter-BOSCH" checked>
Использовал `value` атрибут, чтобы на выходе после нажатия кнопки "Показать" мы имели читабельный текст, значение которого поймет даже случайный прохожий.

2021-01-27 17:16 UTC, Shramkoweb commented on catalog.html
> +      <ol>
Возможно да =)

2021-01-27 17:16 UTC, Shramkoweb commented on catalog.html
> +                <input type="checkbox" name="brands" value="Bosch" id="filter-BOSCH" checked>
А есть другие варианты?

2021-01-27 17:26 UTC, Shramkoweb requested changes

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +        <label for="search"></label>
Пустой лейбл?

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +          <p>Перфораторы</p>
Для единообразия - это a только без href

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +          <a href="catalog.html">Каталог</a>
мы сейчас на странице Перфораторы - каталог не может быть и страницей другого каталога)

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +                <label for="filter-batteries">Аккумуляторные</label>
Зачем везде приставка filter ?

Если ты хочешь улучшить читаемость типа для бекендера, то не стоит. Бекендер и так понимает, что по этому пути прилетят фильтры и по сути этот префикс лишний

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +            <p><s>30500 Р.</s></p>
Может тут и `p` тогда не нужен?

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +        <ul>
А тут не ol - по прошлой твоей аналогии?

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +      <footer role="contentinfo">
Этот ариа нужен для `div`
![image](https://user-images.githubusercontent.com/42001531/106028938-3c3f1600-60d5-11eb-835d-4ec7b597f23f.png)

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +      <footer role="contentinfo">
Я бы в целом свел бы к минимуму ариа, это реально сложная тема и ей можно попортить =)

Так что вставляй только то в чем уверен на 100000% =)

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +          </p>
```suggestion
          <p>
            Обратная связь:
            <a href="mailto:mail@htmlacademy.ru">mail@htmlacademy.ru</a>
          </p>
```

2021-01-27 17:26 UTC, Shramkoweb commented on catalog.html
> +          </p>
```suggestion
          <p>
            Разработано —
            <a href="https://htmlacademy.ru/intensive/htmlcss">htmlacademy.ru</a>
          </p>
```

2021-01-27 17:26 UTC, Shramkoweb commented on index.html
> +    <footer role="contentinfo">
remove

2021-01-27 19:47 UTC, ayqod commented on catalog.html
> +        <ul>
Неа) Потому что пагинация -- по сути свобода выбора, а хлебные крошки -- четкая хронология пути следования к конечной точке:)

2021-01-27 22:36 UTC, ayqod commented on catalog.html
> +                <input type="checkbox" name="brands" value="Bosch" id="filter-BOSCH" checked>
Да. Тупо сделать, как в домашке Барбершопа и не париться. Так процентов 90% по-моему и сделали, чтобы время ни свое, ни наставника не терять))

2021-01-27 22:38 UTC, ayqod commented on catalog.html
> +        <label for="search"></label>
Ну да, в прошлом пр ты вроде как одобрил это с помощью эмоджи) 
А если не пустой, то текст лейбла потом просто скроем через цсс?

2021-01-27 22:41 UTC, ayqod commented on catalog.html
> +          <a href="catalog.html">Каталог</a>
✅

2021-01-27 22:41 UTC, ayqod commented on catalog.html
> +          <p>Перфораторы</p>
✅

2021-01-27 22:43 UTC, ayqod commented on catalog.html
> +                <label for="filter-batteries">Аккумуляторные</label>
✅ А вот тут я наоборот просто следовал домашке, отсюда и приставка эта засела в голове)

2021-01-27 22:50 UTC, ayqod commented on catalog.html
> +          </p>
✅ Ни в коем случае не переношу ответственность, но просто чтобы открыть тайну природы рождения этой привычки:

![image](https://user-images.githubusercontent.com/59294279/106064486-9f936d00-6102-11eb-85d4-037697291c94.png)

Думал им можно доверять:)

2021-01-27 22:52 UTC, ayqod commented on catalog.html
> +          </p>
✅

2021-01-27 23:01 UTC, ayqod commented on catalog.html
> +      <footer role="contentinfo">
Да, но я руководствовался вот этой цитатой из текста w3c спецификации:

![image](https://user-images.githubusercontent.com/59294279/106065638-3d3b6c00-6104-11eb-8c85-a3e76b4ab1e3.png)

Но я в любом случае согласен, что так как полного понимания у меня еще нет + это забегание вперед, то нет смысла заблаговременно делать себе мозг:)

2021-01-27 23:04 UTC, ayqod commented on catalog.html
> +            <p><s>30500 Р.</s></p>
Я тоже вначале так думал, а потом мне попалось уот это уот:
![image](https://user-images.githubusercontent.com/59294279/106065897-9e633f80-6104-11eb-9f3c-e6b92bd297ff.png)

Мне без разницы, как скажешь))

2021-01-27 23:18 UTC, ayqod commented on index.html
> +    <footer role="contentinfo">
✅

2021-01-27 23:26 UTC, ayqod commented on catalog.html
> +                <input type="checkbox" name="brands" value="Bosch" id="filter-BOSCH" checked>
Чтобы на выходе была запись вида `brands — [Bosch, Makita]`? Неа, не знаю. 
Если делать, как в домашке (без value и в name прописать названия брендов), то вместо лаконичного результата получится вот такое вот:

```
Bosch — on
Makita — on
```

2021-01-28 11:45 UTC, Shramkoweb commented on catalog.html
> +                <input type="checkbox" name="brands" value="Bosch" id="filter-BOSCH" checked>
Ну тут все зависит от того, какой вариант ты хочешь получить.

2021-01-28 11:46 UTC, Shramkoweb commented on catalog.html
> +        <label for="search"></label>
Что-то я такого не помню =) Да нужен сктрый текст

2021-01-28 11:48 UTC, Shramkoweb commented on catalog.html
> +            <p><s>30500 Р.</s></p>
Пускай остается )

2021-01-28 11:48 UTC, Shramkoweb commented on catalog.html
> +        <ul>
Согласен

2021-01-28 11:49 UTC, Shramkoweb commented on catalog.html
> +          </p>
Не, такое форматирование выглядит как будто где-то потерялся закрывающий тег.

2021-01-28 13:12 UTC, ayqod commented on catalog.html
> +            <p><s>30500 Р.</s></p>
✅

2021-01-28 13:13 UTC, ayqod commented on catalog.html
> +          </p>
Да, согласен.

2021-01-28 13:16 UTC, Shramkoweb approved these changes

2021-01-28 13:16 UTC, merged