4. Графика всех страниц
htmlacademy-htmlcss/1408611-technomart-30 pull request #4
Opened 2021-02-02 17:58 UTC by ayqod

2021-02-02 17:59 UTC, ayqod reviewed
All images optimized

2021-02-02 18:58 UTC, Shramkoweb requested changes

2021-02-02 18:58 UTC, Shramkoweb commented on catalog.html
> +    <link rel="manifest" href="manifest.webmanifest">
Это точно нужно?)

2021-02-02 18:58 UTC, Shramkoweb commented on catalog.html
> +              <img src="./img/BFG2000.jpg" width="127" height="112" alt="Перфоратор BOSCH BFG 3000">
Я бы рекомендовал называть все файлы с маленькой буквы. Но не надо менять, может появится баг))

2021-02-02 18:58 UTC, Shramkoweb commented on img/icons/icon-materials.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 44 65"><path fill="#fff" d="M37.91 30.44V41.3s.1 2.73-2.82 2.73c-3.07 0-3.13-2.73-3.13-2.73v-6.42c0-.24-.34-1.9-2.32-1.9-2.62 0-2.67 1
Стоит ли у тебя editorconfig ?? Судя по всему нет пустой строки в конце файлов, а он за это отвечает.

2021-02-02 19:23 UTC, ayqod commented on catalog.html
> +              <img src="./img/BFG2000.jpg" width="127" height="112" alt="Перфоратор BOSCH BFG 3000">
так если я переименую изображения + путь к ним, то что за баг будет?)

2021-02-02 19:24 UTC, ayqod commented on img/icons/icon-materials.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 44 65"><path fill="#fff" d="M37.91 30.44V41.3s.1 2.73-2.82 2.73c-3.07 0-3.13-2.73-3.13-2.73v-6.42c0-.24-.34-1.9-2.32-1.9-2.62 0-2.67 1
Установлен, да. Может дело в том, что эти свг файлы были оптимизированы и я их даже в ВС коде не открывал. Сразу в папку скидывал.

2021-02-02 19:26 UTC, ayqod commented on catalog.html
> +    <link rel="manifest" href="manifest.webmanifest">
Если честно, то про фавиконки я вспомнил уже под конец самый. 
Делал как показано в демке Барбершопа, особо не разбираясь в деталях.

2021-02-02 19:31 UTC, ayqod commented on catalog.html
> +    <link rel="manifest" href="manifest.webmanifest">
ааа, я понял, в 6 строке вижу. Поправлю)

2021-02-02 19:32 UTC, ayqod commented on catalog.html
> +    <link rel="manifest" href="manifest.webmanifest">
✅

2021-02-02 19:42 UTC, ayqod commented on catalog.html
> +              <img src="./img/BFG2000.jpg" width="127" height="112" alt="Перфоратор BOSCH BFG 3000">
✅ Переименовал, вроде все нормально)

2021-02-03 09:12 UTC, Shramkoweb commented on catalog.html
> +              <img src="./img/BFG2000.jpg" width="127" height="112" alt="Перфоратор BOSCH BFG 3000">
Бывает, что потом глючит гитхаб. Он видит файлы со старым именем с большой/маленькой буквы.

2021-02-03 09:13 UTC, Shramkoweb approved these changes

2021-02-03 09:13 UTC, merged