5. Стилизация главной страницы
htmlacademy-htmlcss/1408611-technomart-30 pull request #5
Opened 2021-02-08 17:40 UTC by ayqod

2021-02-08 17:49 UTC, Shramkoweb requested changes
1. Убери вложенные слекторы
2. Отформатировать код

2021-02-08 17:49 UTC, Shramkoweb commented on catalog.html
> +        <address class="header-address">г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</address>
Мы если что можем тут использовать БЕМ, если хочешь)

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +}
Я бы все таки вынес в те классы. где это нужно будет

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +  line-height: 24px;
У тебя же они по дефолту?

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +.nav-searchbar:active
Отсуп между селекторами

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +}
Отступ
```suggestion
.menu-bar-cart:active {
  opacity: 0.5;
}

.nav-searchbar:focus {
  background-color: var(--color-white);
}

.menu-bar-checkout {
  color: inherit;
  background-color: var(--color-green-2);
}

.menu-bar-checkout:active {
  opacity: 0.5;
}
```

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +.header-phone a {
Класс на `a` ?

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +.header-menu-bar a {
Класс на `a` ?

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +  line-height: 21px;
Точно?

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +  list-style: none;
Видишь - ты же всеравно сброс стилей списка пишешь))

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +.nav-list-item a {
Класс на `a` ?

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +.featured-item h3 {
Уберай вложенность)

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +.button {
Падинги кнопка не нужны?

2021-02-08 17:49 UTC, Shramkoweb commented on css/style.css
> +.button {
https://isqua.ru/blog/2016/06/19/crash-test-viorstki/

2021-02-08 17:51 UTC, ayqod commented on catalog.html
> +        <address class="header-address">г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</address>
Не-не, не хочу преждевременно. Щас я на этом уровне хотя бы раскачаюсь :-)

2021-02-08 17:52 UTC, Shramkoweb commented on catalog.html
> +        <address class="header-address">г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8</address>
Ок

2021-02-08 17:59 UTC, ayqod commented on css/style.css
> +  line-height: 21px;
А шо именно не так?) Цвет верный, размеры правильные, пусть вроде указан же верно -- все ссылки, родитель которых хедер-меню-бар....

2021-02-08 18:00 UTC, ayqod commented on css/style.css
> +  line-height: 21px;
аааа...вложенность

2021-02-08 18:25 UTC, Shramkoweb commented on css/style.css
> +  line-height: 21px;
Не, я про то что высота строки = размеру шрифта. Точно не баг и так в макете?

2021-02-08 21:05 UTC, ayqod commented on css/style.css
> +}
✅

2021-02-08 21:48 UTC, ayqod commented on css/style.css
> +  line-height: 24px;
✅

2021-02-08 21:56 UTC, ayqod commented on css/style.css
> +.nav-searchbar:active
✅

2021-02-08 21:57 UTC, ayqod commented on css/style.css
> +}
✅

2021-02-08 21:59 UTC, ayqod commented on css/style.css
> +  list-style: none;
✅

2021-02-08 22:01 UTC, ayqod commented on css/style.css
> +  line-height: 21px;
![image](https://user-images.githubusercontent.com/59294279/107286880-d99d3100-6a69-11eb-9a51-8c8ce3be856b.png)

Да, в макете так. Но не факт, что это не баг, который либо исправят позже, либо сделают фичей:)

2021-02-08 22:25 UTC, ayqod commented on css/style.css
> +.button {
В этом задании про отступы речи не было, но я добавлю :)
Они чуть позже потом будут.

2021-02-08 22:36 UTC, ayqod commented on css/style.css
> +.button {
✅

2021-02-08 22:43 UTC, ayqod commented on css/style.css
> +.nav-list-item a {
✅

2021-02-08 22:48 UTC, ayqod commented on css/style.css
> +.heading-blue h2 {
О_о! Просто поражаюсь самому себе, не более. Исправил ✅

2021-02-08 22:57 UTC, ayqod commented on css/style.css
> +.main-service p,
9 смешариков из 10 просто

```suggestion
```

2021-02-08 23:31 UTC, ayqod commented on css/style.css
> +.featured-item h3 {
✅

2021-02-08 23:32 UTC, ayqod commented on css/style.css
> +.header-menu-bar a {
✅

2021-02-08 23:32 UTC, ayqod commented on css/style.css
> +.header-phone a {
✅

2021-02-09 13:47 UTC, Shramkoweb approved these changes
Проверь по поводу нормалайза в критериях - как его верно подключать.

2021-02-09 13:47 UTC, merged