6. Сетка на флексах
htmlacademy-htmlcss/1408611-technomart-30 pull request #9
Opened 2021-03-09 17:34 UTC by ayqod

2021-03-10 16:57 UTC, Shramkoweb requested changes

2021-03-10 16:57 UTC, Shramkoweb commented on catalog.html
> +            <img src="/img/logo-technomart.svg" width="108" height="18" alt="Логотип сайта">
Обычно логитипы делают как декорацию
role="presentation" и aria-hidden="true"

2021-03-10 16:57 UTC, Shramkoweb commented on css/style.css
> +  height: 19px;
Тут же по твоему стили отступ должен быть?

2021-03-10 16:57 UTC, Shramkoweb commented on css/style.css
> +  ;
Форматирование

2021-03-10 16:57 UTC, Shramkoweb commented on css/style.css
> +  content: url(../img/layer-delivery.png);
```suggestion
  content: url("../img/layer-delivery.png"); 
``` 
??

2021-03-10 16:57 UTC, Shramkoweb commented on css/style.css
> +  background: url(../img/logo-technomart.svg) var(--basic-red) no-repeat center;
урлу в кавычки?

2021-03-10 16:57 UTC, Shramkoweb commented on css/style.css
> +  background: url(../img/logo-technomart.svg) var(--basic-red) no-repeat center;
И разнеси плиз все отдельно)) background

2021-03-10 16:57 UTC, Shramkoweb commented on css/style.css
> +.footer-nav-wrap ul li:not(:first-child) {
Нельзя ли сразу как-то клас кинуть на li?

2021-03-10 16:57 UTC, Shramkoweb commented on css/style.css
> +  font-family: "PT Sans",Arial,sans-serif;
```suggestion
  font-family: "PT Sans", Arial, sans-serif;
```

2021-03-10 16:57 UTC, Shramkoweb commented on index.html
> +              <div class="slider-heading">
hgroup почитай - вроде полезный тег тут будет

2021-03-10 22:51 UTC, ayqod commented on catalog.html
> +            <img src="/img/logo-technomart.svg" width="108" height="18" alt="Логотип сайта">
✅

2021-03-10 23:54 UTC, ayqod commented on css/style.css
> +  height: 19px;
✅

2021-03-11 00:15 UTC, ayqod commented on css/style.css
> +  ;
✅

2021-03-11 00:17 UTC, ayqod commented on css/style.css
> +  content: url(../img/layer-delivery.png);
Жаль, что оно без кавычек все равно отображается:)

2021-03-11 00:18 UTC, ayqod commented on css/style.css
> +  background: url(../img/logo-technomart.svg) var(--basic-red) no-repeat center;
✅

2021-03-11 00:20 UTC, ayqod commented on css/style.css
> +  background: url(../img/logo-technomart.svg) var(--basic-red) no-repeat center;
✅

2021-03-11 00:22 UTC, ayqod commented on css/style.css
> +.footer-nav-wrap ul li:not(:first-child) {
Можно, просто жалко :) Учили-учили эти псевдоклассы, а не применяем(

2021-03-11 00:34 UTC, ayqod commented on css/style.css
> +.footer-nav-wrap ul li:not(:first-child) {
```suggestion
.footer-top-links,
.footer-bottom-links {
  padding-left: 58px;
}

.footer-links-no-padding {
  padding: 0;
}
```

типа такого? Можно еще конечно опять через :not но уже по классу

2021-03-11 00:36 UTC, ayqod commented on css/style.css
> +  font-family: "PT Sans",Arial,sans-serif;
✅ Поменял на соответствующую переменную.

2021-03-11 00:40 UTC, ayqod commented on index.html
> +              <div class="slider-heading">
✅ Добавил
![image](https://user-images.githubusercontent.com/59294279/110718168-20ba4580-8213-11eb-8b75-bf989293e8fc.png)

2021-03-11 00:44 UTC, ayqod commented on index.html
> +              <div class="slider-heading">
✅ Добавил

![image](https://user-images.githubusercontent.com/59294279/110718420-9de5ba80-8213-11eb-9267-5468e09509d6.png)

2021-03-11 08:36 UTC, Shramkoweb commented on css/style.css
> +.footer-nav-wrap ul li:not(:first-child) {
Псевдоклассы ок  - плохо вложеность `.footer-nav-wrap ul li`

2021-03-11 08:36 UTC, Shramkoweb commented on index.html
> +              <div class="slider-heading">
Круто - это трело?

2021-03-11 08:37 UTC, Shramkoweb approved these changes

2021-03-11 08:37 UTC, merged